Repository TotalCross/totalcross, pull requests merged in 2020-11, with the labels that each got.

#183 image: using lockChanges now correctly prevents texture recreation
  TotalCrossVM/src/nm/ui/GraphicsPrimitives_c.h
  TotalCrossVM/src/nm/ui/image_Image.c
Labels: bug

#173 bugfix #124: no upscaling of font, fixing memory consumption
  TotalCrossSDK/src/main/java/totalcross/ui/FloatingLabel.java
Labels: All platforms

#171 litebase: deprecate litebase, as we're ending official support for it
  LitebaseSDK/src/java/litebase/AlreadyCreatedException.java
  LitebaseSDK/src/java/litebase/AlreadyCreatedException4D.java
  LitebaseSDK/src/java/litebase/ComposedIndex.java
  LitebaseSDK/src/java/litebase/DataStreamLB.java
  LitebaseSDK/src/java/litebase/DriverException.java
  LitebaseSDK/src/java/litebase/DriverException4D.java
  LitebaseSDK/src/java/litebase/Entry.java
  LitebaseSDK/src/java/litebase/Index.java
  LitebaseSDK/src/java/litebase/Key.java
  LitebaseSDK/src/java/litebase/LitebaseConnection.java
  LitebaseSDK/src/java/litebase/LitebaseConnection4D.java
  LitebaseSDK/src/java/litebase/LitebaseLex.java
  LitebaseSDK/src/java/litebase/LitebaseMessage.java
  LitebaseSDK/src/java/litebase/LitebaseParser.java
  LitebaseSDK/src/java/litebase/MarkBits.java
  LitebaseSDK/src/java/litebase/MemoryFile.java
  LitebaseSDK/src/java/litebase/Node.java
  LitebaseSDK/src/java/litebase/NormalFile.java
  LitebaseSDK/src/java/litebase/PlainDB.java
  LitebaseSDK/src/java/litebase/PreparedStatement.java
  LitebaseSDK/src/java/litebase/PreparedStatement4D.java
  LitebaseSDK/src/java/litebase/PrimaryKeyViolationException.java
  LitebaseSDK/src/java/litebase/PrimaryKeyViolationException4D.java
  LitebaseSDK/src/java/litebase/ReservedHashtable.java
  LitebaseSDK/src/java/litebase/ResultSet.java
  LitebaseSDK/src/java/litebase/ResultSet4D.java
  LitebaseSDK/src/java/litebase/ResultSetMetaData.java
  LitebaseSDK/src/java/litebase/ResultSetMetaData4D.java
  LitebaseSDK/src/java/litebase/RowIterator.java
  LitebaseSDK/src/java/litebase/RowIterator4D.java
  LitebaseSDK/src/java/litebase/SQLBooleanClause.java
  LitebaseSDK/src/java/litebase/SQLBooleanClauseTree.java
  LitebaseSDK/src/java/litebase/SQLColumnListClause.java
  LitebaseSDK/src/java/litebase/SQLDeleteStatement.java
  LitebaseSDK/src/java/litebase/SQLElement.java
  LitebaseSDK/src/java/litebase/SQLFieldDefinition.java
  LitebaseSDK/src/java/litebase/SQLInsertStatement.java
  LitebaseSDK/src/java/litebase/SQLParseException.java
  LitebaseSDK/src/java/litebase/SQLParseException4D.java
  LitebaseSDK/src/java/litebase/SQLResultSetField.java
  LitebaseSDK/src/java/litebase/SQLResultSetTable.java
  LitebaseSDK/src/java/litebase/SQLSelectClause.java
  LitebaseSDK/src/java/litebase/SQLSelectStatement.java
  LitebaseSDK/src/java/litebase/SQLStatement.java
  LitebaseSDK/src/java/litebase/SQLUpdateStatement.java
  LitebaseSDK/src/java/litebase/SQLValue.java
  LitebaseSDK/src/java/litebase/Table.java
  LitebaseSDK/src/java/litebase/TableNotClosedException.java
  LitebaseSDK/src/java/litebase/TableNotClosedException4D.java
  LitebaseSDK/src/java/litebase/Utils.java
  LitebaseSDK/src/java/litebase/XFile.java
Labels: All platforms

#128 Topic/sdl window fixes macosx
  TotalCrossVM/src/init/tcsdl.cpp
Labels: MacOS, bug

#194 container: fix border not being drawn as it should when setting borde…
  TotalCrossSDK/src/main/java/totalcross/ui/Container.java
Labels: bug

#220 litebase: fixes using litebase
  TotalCrossVM/src/init/settings.c
  TotalCrossVM/src/init/settings.h
  TotalCrossVM/src/litebase/TCVMLib.c
Labels: bug
