Repository TotalCross/totalcross, pull requests merged in 2020-07, with the labels that each got.

#59 Topic/support pixel format argb
  TotalCrossVM/src/nm/ui/android/skia.cpp
Labels: enhancement

#61 Changes Launcher to accept the actual name of the tcz as an argument.
  TotalCrossVM/src/launchers/linux/Launcher.c
Labels: feature

#65 virtualkeyboard: adds a sliding animation to the keyboard
  TotalCrossSDK/src/main/java/totalcross/ui/dialog/keyboard/AlphabetKeyboard.java
  TotalCrossSDK/src/main/java/totalcross/ui/dialog/keyboard/NumericAndSymbolsKeyboard.java
  TotalCrossSDK/src/main/java/totalcross/ui/dialog/keyboard/VirtualKeyboard.java
Labels: feature

#67 jsonobject: removes printStackTrace from opt methods
  TotalCrossSDK/src/main/java/totalcross/json/JSONObject.java
Labels: java

#66 AnonymousUserData: asks user to send anonymous usage statistics
  TotalCrossSDK/src/main/java/tc/Deploy.java
  TotalCrossSDK/src/main/java/tc/tools/AnonymousUserData.java
  TotalCrossSDK/src/main/java/totalcross/Launcher.java
  TotalCrossSDK/src/main/resources/tc/crossy.png
Labels: feature

#68 Cleaning static SDL remnants
  TotalCrossVM/builders/gcc-linux-arm/README.md
  TotalCrossVM/builders/gcc-linux-arm/sdl/build.bat
  TotalCrossVM/builders/gcc-linux-arm/sdl/build.sh
Labels: build, documentation, enhancement

#75 Image.alphaMask: adds support for alphaMask on Skia
  TotalCrossVM/src/nm/ui/GraphicsPrimitives_c.h
  TotalCrossVM/src/nm/ui/android/skia.cpp
  TotalCrossVM/src/nm/ui/android/skia.h
Labels: bug

#76 Game: removes deprecation of this package
  TotalCrossSDK/src/main/java/totalcross/game/AnimatedButton.java
  TotalCrossSDK/src/main/java/totalcross/game/Animation.java
  TotalCrossSDK/src/main/java/totalcross/game/AnimationEvent.java
  TotalCrossSDK/src/main/java/totalcross/game/AnimationHandler.java
  TotalCrossSDK/src/main/java/totalcross/game/GameEngine.java
  TotalCrossSDK/src/main/java/totalcross/game/GameEngineException.java
  TotalCrossSDK/src/main/java/totalcross/game/GameEngineMainWindow.java
  TotalCrossSDK/src/main/java/totalcross/game/HighScoreEntry.java
  TotalCrossSDK/src/main/java/totalcross/game/HighScores.java
  TotalCrossSDK/src/main/java/totalcross/game/Options.java
  TotalCrossSDK/src/main/java/totalcross/game/Sprite.java
  TotalCrossSDK/src/main/java/totalcross/game/TextRenderer.java
Labels: feature

#81 Launcher: avoids attempting to load a missing font file over and over
  TotalCrossSDK/src/main/java/totalcross/Launcher.java
Labels: bug
