Repository TotalCross/totalcross, pull requests merged in 2020-05, with the labels that each got.

#17 Adding bats to run docker
  TotalCrossVM/builders/gcc-linux-arm/sdl/build.bat
  TotalCrossVM/builders/gcc-linux-arm/tcvm/build.bat
  TotalCrossVM/builders/gcc-posix/tcvm/build.bat
Labels: feature

#29 Generic implementation of SDL texture streaming + Skia
  TotalCrossVM/src/event/linux/event_c.h
  TotalCrossVM/src/init/tcsdl.cpp
  TotalCrossVM/src/init/tcsdl.h
  TotalCrossVM/src/nm/ui/android/skia.cpp
  TotalCrossVM/src/nm/ui/android/skia.h
Labels: enhancement

#30 Removes linux Launcher.c folder and renames raspbian/ to linux/
  TotalCrossVM/builders/gcc-linux-arm/launcher/Makefile
  TotalCrossVM/builders/gcc-posix/launcher/Makefile
  TotalCrossVM/src/launchers/linux/Launcher.c
  TotalCrossVM/src/launchers/raspbian/Launcher.c
Labels: enhancement

#32 Feature/templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#33 Fixes FadeAnimation fade not working.
  TotalCrossSDK/src/main/java/totalcross/ui/anim/FadeAnimation.java
Labels: bug
