Repository TotalCross/totalcross, pull requests merged in 2020-08, with the labels that each got.

#95 simulator: correctly skips the key arg
  TotalCrossSDK/src/main/java/totalcross/Launcher.java
Labels: All platforms, bug, java

#97 libgpiod: fixes crash when running on a system without libgpiod
  TotalCrossVM/src/nm/io/device/gpiod/posix/gpiodLib.c
Labels: Linux ARM, bug

#99 Avoid SDL display bounds dependency
  TotalCrossVM/src/init/tcsdl.cpp
Labels: Linux, Linux ARM, c++

#104 Shows hint to help if get error in CreateRenderer
  TotalCrossVM/src/init/tcsdl.cpp
Labels: Linux, Linux ARM, c++

#109 cmake: fix path to Motorola.vcproj
  TotalCrossVM/CMakeLists.txt
Labels: bug, build

#113 Fix arrow operator end EOL
  TotalCrossVM/modules/skia/include/private/SkTemplates.h
Labels: build, c++

#112 SDL: improve IO messages
  TotalCrossVM/src/init/tcsdl.cpp
Labels: Linux, Linux ARM, c++

#115 sdl: sizes and fullscreen update
  TotalCrossVM/src/init/tcsdl.cpp
Labels: Linux, Linux ARM, c++

#134 sdl: use `flags` to adjust window sizes
  TotalCrossVM/src/init/tcsdl.cpp
Labels: Linux, Linux ARM, MacOS
