Repository TotalCross/totalcross, pull requests merged in 2020-12, with the labels that each got.

#221 launcher: fixes stackoverflow when using ZipStream on wince
  TotalCrossVM/CMakeLists.txt
  TotalCrossVM/vc2008/Launcher.vcproj
Labels: bug

#227 xml: fix encoding to support more characters
  TotalCrossSDK/src/main/java/totalcross/ui/html/Document.java
  TotalCrossSDK/src/main/java/totalcross/util/I18N.java
  TotalCrossSDK/src/main/java/totalcross/xml/AttributeList.java
  TotalCrossSDK/src/main/java/totalcross/xml/DumpXml.java
  TotalCrossSDK/src/main/java/totalcross/xml/XmlReadableByteArray.java
  TotalCrossSDK/src/main/java/totalcross/xml/XmlReadablePort.java
  TotalCrossSDK/src/main/java/totalcross/xml/XmlReadableSocket.java
  TotalCrossSDK/src/main/java/totalcross/xml/XmlReader.java
  TotalCrossSDK/src/main/java/totalcross/xml/XmlTokenizer.java
  TotalCrossSDK/src/main/java/totalcross/xml/rpc/XmlRpcClient.java
  TotalCrossSDK/src/main/java/totalcross/xml/soap/SOAP.java
Labels: All platforms, bug

#239 cicd: fix cyclical dependency for PRs
  .github/workflows/main.yml
Labels: bug, enhancement, feature

#245 revert: e420cb it's not working as it should
  .github/workflows/commit.yml
Labels: bug

#244 build: fix glibc build error
  TotalCrossVM/CMakeLists.txt
  TotalCrossVM/src/nm/io/device/gpiod/posix/gpiodLib.c
  TotalCrossVM/src/nm/ui/android/skia.cpp
Labels: Linux, Linux ARM, build

#247 cicd: do not build the containers anymore
  .github/workflows/main.yml
Labels: build, enhancement

#251 cicd: copy *.jar files because we need them to release versions
  .github/workflows/package.yml
Labels: build, enhancement
