Repository TotalCross/totalcross, pull requests merged in 2021-01, with the labels that each got.

#261 deploy: add Linux ARM 64 to linux_arm platform deploy
  TotalCrossSDK/src/main/java/tc/Deploy.java
  TotalCrossSDK/src/main/java/tc/tools/deployer/Deployer4LinuxArm64.java
Labels: Linux ARM

#281 objects: fix to properly call Objects4D when using jata.util.Objects
  TotalCrossSDK/src/main/java/jdkcompat/util/Objects4D.java
Labels: All platforms

#278 sdl: fixes segfault during SDL initialization
  TotalCrossVM/src/init/tcsdl.cpp
Labels: Linux ARM, bug

#279 sdl: force usage of software renderer for linux arm
  TotalCrossVM/src/init/tcsdl.cpp
Labels: bug

#283 sdl: fixes screen not updating after the window size is changed
  TotalCrossVM/src/event/linux/event_c.h
  TotalCrossVM/src/init/tcsdl.cpp
  TotalCrossVM/src/init/tcsdl.h
Labels: bug

#282 xml: fix xml parse by using only one implementation to parse file
  TotalCrossSDK/src/main/java/totalcross/xml/XmlTokenizer4D.java
  TotalCrossVM/CMakeLists.txt
  TotalCrossVM/src/init/nativeProcAddressesTC.c
  TotalCrossVM/src/nm/NativeMethods.h
  TotalCrossVM/src/nm/NativeMethods.txt
  TotalCrossVM/src/nm/NativeMethodsPrototypes.txt
  TotalCrossVM/src/nm/instancefields.h
  TotalCrossVM/src/nm/xml/xml_XmlTokenizer.c
  TotalCrossVM/src/nm/xml/xml_XmlTokenizer_test.h
  TotalCrossVM/vc2008/TCVM.vcproj
Labels: All platforms

#255 Contributing guidelines enhancement
  CONTRIBUTING.md
Labels: documentation, enhancement
